# Generated by Django 5.2.3 on 2025-06-14 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="constructionsite",
            name="progress",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Прогресс",
            ),
        ),
        migrations.AddField(
            model_name="constructionsite",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "Планирование"),
                    ("in_progress", "В процессе"),
                    ("on_hold", "На паузе"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="planning",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
