# Generated by Django 5.2.3 on 2025-06-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0002_constructionsite_progress_constructionsite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionsite",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Адрес объекта"),
        ),
    ]
