# Generated by Django 5.2.3 on 2025-06-14 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0003_alter_constructionsite_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="constructionsite",
            name="workers",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="sites_working",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Рабочие",
            ),
        ),
    ]
