# Generated by Django 5.2.3 on 2025-06-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("construction", "0006_task_priority_alter_task_construction_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Срок выполнения"
            ),
        ),
    ]
